services:
  japanese-freq:
    image: japanese-freq:latest
    env_file:
      - .env
    volumes:
      - ./output:/usr/src/app/output
      - ./input:/usr/src/app/input
      - ./dictionaries:/usr/src/app/dictionaries
      - ./.ignorelist.json:/usr/src/app/.ignorelist
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
