name: PR Lint

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  client-lint:
    name: Client Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.2.0"

      - name: Install client dependencies
        run: cd client && npm ci

      - name: Run client lint
        run: make client/lint

  server-lint:
    name: Server Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install server dependencies
        run: cd server && pip install -r requirements.txt

      - name: Run server lint
        run: make server/lint
